### ISSUE TITLE
ImportError: cannot import name 'maybe_cythonize_extensions'

### ISSUE THREAD

**Issue by mhlr** [neonnnnn/pyrfm#4]
`python setup.py install` fails with `ImportError: cannot import name 'maybe_cythonize_extensions'`

```
+ pip install -r requirements.txt
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1)) (1.18.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2)) (1.4.1)
Requirement already satisfied: cython in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3)) (0.29.19)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 4)) (0.22.2.post1)
Requirement already satisfied: pytest in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 5)) (3.6.4)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->-r requirements.txt (line 4)) (0.15.1)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from pytest->-r requirements.txt (line 5)) (1.8.1)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.6/dist-packages (from pytest->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.6/dist-packages (from pytest->-r requirements.txt (line 5)) (0.7.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/dist-packages (from pytest->-r requirements.txt (line 5)) (19.3.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from pytest->-r requirements.txt (line 5)) (47.1.1)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from pytest->-r requirements.txt (line 5)) (1.12.0)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.6/dist-packages (from pytest->-r requirements.txt (line 5)) (8.3.0)
```

```
+ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    zip_safe=False
  File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/core.py", line 137, in setup
    config = configuration()
  File "setup.py", line 16, in configuration
    config.add_subpackage('pyrfm')
  File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/misc_util.py", line 1035, in add_subpackage
    caller_level = 2)
  File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/misc_util.py", line 1004, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/misc_util.py", line 917, in _get_configuration_from_setup_py
    ('.py', 'U', 1))
  File "/usr/local/lib/python3.6/dist-packages/numpy/compat/py3k.py", line 159, in npy_load_module
    return importlib.machinery.SourceFileLoader(name, fn).load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "pyrfm/setup.py", line 1, in <module>
    from sklearn._build_utils import maybe_cythonize_extensions
ImportError: cannot import name 'maybe_cythonize_extensions'
```

**Comment by neonnnnn** [comment]
Thank you.
`maybe_cythonize_extensions` has been removed from scikit-learn recently, so I replaced it with `cythonize_extensions`. Moreover, pyrfm had used `scipy.fftpack`, which is now considered legacy, so I replaced it with `scipy.fft`.

Can you install and use updated code [update-dependency-issue4](/neonnnnn/pyrfm/tree/update-dependency-issue4)? (I succeeded in installing pyrfm in Python 3.6, 3.7, and 3.8).

**Comment by amirdib** [comment]
> Thank you.
> `maybe_cythonize_extensions` has been removed from scikit-learn recently, so I replaced it with `cythonize_extensions`. Moreover, pyrfm had used `scipy.fftpack`, which is now considered legacy, so I replaced it with `scipy.fft`.
> 
> Can you install and use updated code [update-dependency-issue4](/neonnnnn/pyrfm/tree/update-dependency-issue4)? (I succeeded in installing pyrfm in Python 3.6, 3.7, and 3.8).

[update-dependency-issue4](/neonnnnn/pyrfm/tree/update-dependency-issue4) fixes the issue. Succesfully installed with python 3.7.3 and last scikit-learn version. Maybe requirements should be versioned.

**Comment by neonnnnn** [comment]
@amirdib Thank you for verifying! I specified versions and merged [update-dependency-issue4](https://github.com/neonnnnn/pyrfm/tree/update-dependency-issue4) into master.
